class AlertError:
    alert_illegal_price = "价格不合法"
    alert_illegal_gap = "Gap不合法"
    alert_illegal_step = "Step不合法"
    alert_illegal_stop_price = "止损价不合法"
    alert_illegal_price_tick_size = "价格必须是最小变动价格的整数倍"
    alert_illegal_input_limit = "最多s输入8位整数和8位小数"
    alert_illegal_order_price_tick_size = "下单价必须是最小变动价格的整数倍"
    alert_illegal_order_stop_price_tick_size = "止损价必须是最小变动价格的整数倍"
    alert_illegal_lots = "手数不合法"
    alert_message_lots = "请输入手数"
    alert_message_price = "请输入价格"
    alert_message_gap = "请输入Gap"
    alert_message_stop_loss = "请输入止损"
    alert_illegal_stop_loss = "止损不合法"
    alert_message_stop_profit = "请输入止盈"
    alert_illegal_stop_profit = "止盈不合法"
    alert_message_stop_price = "请输入止损价"
    alert_title_succeed = "下单请求发送成功!"
    alert_message_succeed = "下单成功" or "订单详情"
    alert_message_StPx = "请输入StPx"
    alert_message_chunk_size = "请输入暴露数量"
    alert_message_min_quantity = "请输入最小数量"
    alert_buy_order_illegal_StPx = "买单StPx需小于等于价格"
    alert_sell_order_illegal_StPx = "卖单StPx需大于等于价格"
    alert_message_buy_order_rejected = "New order rejected, Buy order stop price must be above last trade price"
    alert_message_sell_order_rejected = "New order rejected, Sell order stop price must be below last trade price"
    hint_message = "输入长度不能超过255个字符"




