class LangEn:
    englishStrings = {"alert_illegal_price": "价格不合法",
                      "alert_illegal_gap": "Gap不合法",
                      "alert_illegal_step": "Step不合法",
                      "alert_illegal_stop_price": "止损价不合法",
                      "alert_illegal_price_tick_size": "价格必须是最小变动价格的整数倍",
                      "alert_illegal_input_limit": "最多输入8位整数和8位小数",
                      "alert_illegal_order_price_tick_size": "下单价必须是最小变动价格的整数倍",
                      "alert_illegal_lots": "手数不合法",
                      "alert_message_lots": "请输入手数",
                      "alert_message_price": "请输入价格",
                      "alert_message_gap": "请输入Gap",
                      "alert_message_stop_loss": "请输入止损",
                      "alert_illegal_stop_loss": "止损不合法",
                      "alert_message_stop_profit": "请输入止盈",
                      "alert_illegal_stop_profit": "止盈不合法",
                      "alert_message_stop_price": "请输入止损价",
                      "alert_message_close_pxdiff": "请输入平仓价差",
                      "alert_illegal_close_pxdiff": "平仓价差不合法",
                      "alert_message_open_pxdiff": "请输入开仓价差",
                      "alert_illegal_open_pxdiff": "开仓价差不合法",
                      "alert_message_single": "请输入单次",
                      "alert_message_single_and_lots": "单次手数必须小于或等于手数",
                      "alert_message_price_diff": "请输入价差",
                      "alert_illegal_price_diff": "价差不合法",
                      "alert_message_order_interval": "请输入下单间隔",
                      "alert_illegal_order_interval": "下单间隔不合法",
                      "alert_message_cancel_order_interval": "请输入撤单间隔",
                      "alert_illegal_cancel_order_interval": "撤单间隔不合法",
                      "alert_illegal_end_time": "结束时间必须超过当前时间",
                      "alert_illegal_time_interval": "时间间隔不合法",
                      "alert_message_cancel_limit": "请输入撤单上限",
                      "alert_message_price_limit": "请输入限价",
                      "alert_illegal_price_limit": "限价不合法",
                      "alert_illegal_cancel_order_interval_value": "撤单间隔必须小于或等于下单间隔",
                      "alert_illegal_price_diff_tick_size": "价差必须是最小变动价格的整数倍",
                      "alert_illegal_close_pxdiff_tick_size": "平仓价差必须是最小变动价格的整数倍",
                      "alert_illegal_open_pxdiff_tick_size": "开仓价差必须是最小变动价格的整数倍",
                      "alert_message_times": "请输入数量",
                      "alert_illegal_times": "数量不合法",
                      "alert_message_StPx": "请输入StPx",
                      "alert_message_chunk_size": "请输入暴露数量",
                      "alert_message_min_quantity": "请输入最小数量",
                      "alert_buy_order_illegal_StPx": "买单StPx需小于等于价格",
                      "alert_sell_order_illegal_StPx": "卖单StPx需大于等于价格",
                      "alert_message_buy_order_rejected": "New order rejected, Buy order stop price must be above last trade price.",
                      "alert_message_sell_order_rejected": "New order rejected, Sell order stop price must be below last trade price.",
                      "hint_message": "输入长度不能超过255个字符",


                      "networking_issue": "There seems to be something wrong with the network",

                      "prompt_username": "Username",
                      "prompt_password": "Password",
                      "action_sign_in": "Log in",
                      "error_field_required": "This field is required",
                      "not_show_disclaimer": "Don\'t remind me next time",
                      "network_disconnected": "No internet connection",
                      "network_check_please": "Please check your network connection",
                      "session_timed_out_please_log_in_again": "Session timed out, please log in again",
                      "shut_down": "Close",
                      "order_type_title": "Order type",
                      "edit": "Edit",
                      "resume": "Resume",
                      "pause": "Pause",
                      "action_settings": "Settings",
                      "bulletin": "Bulletin",

                      "remember_device": "Trust this device?",
                      "no_need_otp": "No need for OTP in a period",

                      "get_system_info_tip": "Agree to get system info according to CN regulators",

                      "ERROR_INTERNAL": "Internal Error",
                      "ERROR_CONNECTION": "Can not connect to server",
                      "ERROR_SERVER": "Unknown error",
                      "ERROR_PERMISSION": "Permission Denied",
                      "ERROR": "Error",
                      "Cancel": "Cancel",
                      "Okay": "Okay",
                      "DISCONNECTED": "Disconnected!",
                      "title_quotes": "Quote",
                      "title_positions": "Positions",
                      "title_messages": "Messages",
                      "title_logout": "Logout",
                      "logout_tip": "Are you sure to logout?",
                      "login_failed": "Login failed",
                      "action_done": "Done",
                      "buy": "Buy",
                      "sell": "Sell",
                      "title_strategies": "Strategies",
                      "auto": "Auto",
                      "title_edit_contracts": "Management",
                      "title_modify": "Modify",
                      "title_new_order": "New order",
                      "title_new_contract": "Select contracts",
                      "powered_by_atplatform": "Powered by ATPlatform",
                      "support_ipv6_network": "Support IPv6 network",
                      "error_save": "Save Failed",
                      "fail_submit_order": "Order Submit Failed",
                      "yes": "Yes",
                      "no": "No",
                      "invalid_formula": "Invalid formula",
                      "cancel_order_prompt": "Are you sure to cancel this order?",
                      "fail_position": "Get Positions Failed",
                      "bid": "Bid",
                      "offer": "Offer",
                      "account": "Account",
                      "price": "Price",
                      "lots": "Lots",
                      "time_option": "TIF",
                      "loss_diff": "Loss diff",
                      "profit_diff": "Profit diff",
                      "diff": "Diff",
                      "chase": "Chase",
                      "type": "Type",
                      "split": "Split",
                      "formula": "Formula",
                      "digits": "Digits",
                      "strategy_name": "Strategy name",
                      "orderfilled": "OrderFilled",
                      "active_leg_n":"Active Leg %c",
                      "prior_leg_n":"Prior Leg %c",
                        "active_leg": "Active Leg",
                      "prior_leg": "Prior Leg",

                      "send_success": "Sent Successfully",
                      "logout_done": "Logout Successfully",
                      "order_not_support": "Order Type Not Support",

                      "limit": "Limit",
                      "market": "Market",
                      "stop_price": "STP",
                      "stop_limit": "STL",
                      "iceberg": "ICE",
                      "LIM": "LIM",
                      "order_type_unknown": "unknown",
                      "market_limit": "Market Limit",
                      "iceberg_stepper_title": "Chunk Size",

                      "market_price": "Market",

                      "min_quantity": "Min Quantity",

                      "CloseYesterday": "Close Yesterday",
                      "open": "Open",
                      "close": "Close",
                      "offset_flag_auto": "Auto",
                      "closeToday": "Close Today",
                      "c_ct_o": "C-CT-O",
                      "ct_c_o": "CT-C-O",
                      "c_o": "C-O",
                      "ct_o": "CT-O",
                      "cy_o": "CY-O",

                      "change_password": "Change password",
                      "title_change_password": "Change password",
                      "oldpassword": "Old password",
                      "Error1": "Internal server error!",

                      "Error100": "Username or password can\'t be empty!",
                      "Error100_1": "Username or password or verification code can\'t be empty!",
                      "Error101": "Username does not exist!",
                      "Error102": "Username is locked!",
                      "Error103_1": "Password or verification code is error!",
                      "Error104": "Password is expired!",
                      "Error105": "Username is expired!",
                      "Error106": "force to change password!",
                      "Error107": "Trust device is expired!",
                      "Error108": "Token is illegal!",
                      "Error200": "Change password failed!",

                      "Error201": "New password and confirm new password doesn\'t match",
                      "Error202": "New password can not be empty!",
                      "Error203": "Current password isn\'t correct",
                      "Error203_1": "Old password is wrong",
                      "Error204": "New password must contain at least one uppercase letter!",
                      "Error205": "New password must contain at least one lowercase letter!",
                      "Error206": "New password must contain at least one digit!",
                      "Error207": "New password must contain at least %s characters!",
                      "Error208": "New password can not be same with your recent %s password history!",
                      "Error209":"New password must contain at least one non-alphanumeric(%s) character!",
                      "Error210": "New password can not be same with old password!",

                      "Error300": "App version outdated, please update the app!",
                      "Error302": "Failed to get system info according to CN regulators",

                      "Error400": "The authentication has already completed",
                      "Error403": "preorder step is unfinish!",
                      "ErrorMessage": "Please use the latest PC installation version to initialize 2FA!",

                      "ChgPwdSuccess": "Password has been changed successfully",

                      "offset_flag": "Offset Flag",
                      "hedge_flag": "Hedge Flag",

                      "gapprice": "Gap",
                      "stepprice": "Step",

                      "speculation": "Speculation",
                      "arbitrage": "Arbitrage",
                      "hedge": "Hedge",
                      "title_group_manager": "Group management",
                      "ContractName": "Contract Name",
                      "ContractCode": "Contract Code",

                      "change_value": "Chg",
                      "change_rate": "%Chg",

                      "error_illegal_lot": "Illegal lot",
                      "error_formula": "Illegal formula value!",

                      "error": "Error",
                      "cancel": "Cancel",
                      "ok": "OK",
                      "error_delete": "Delete Fail",
                      "error_illegal_parameter": "Illegal Parameter",
                      "StartTime": "Start time",
                      "EndTime": "End time",
                      "isn_invalid": "isn\'t valid",
                      "contract_invalid": "Contract isn\'t valid",
                      "contract_not_exist": "Contract not exists!",
                      "bp_account": "Account",
                      "bp_broker": "Broker",
                      "bp_margin": "Margin",
                      "bp_equity": "Equity",
                      "bp_equity_margin": "Equity-Margin",
                      "bp_exposure": "Exposure",
                      "loading": "loading...",

                      "error_minQty": "Minimum quantity can\'t be larger than lots",
                      "please_input_minQty": "Please input min quantity",
                      "please_input_max_iceberg_chunk_size": "Please input chunk size",

                      "confirm": "Confirm",

                      "trader": "Trade",
                      "min1": "1m",
                      "min5": "5m",
                      "min15": "15m",
                      "min30": "30m",
                      "h1": "1h",
                      "KLineTitle": "K Chart",
                      "date": "Date",
                      "dd1": "1D",

                      "welcome_back": "Hello, \nwelcome back",
                      "back": "Back",
                      "input_username": "Please input username",
                      "input_password": "Please input password",
                      "input_old_password": "Please input old password",
                      "input_new_password": "Please input new password",
                      "verification_code": "Verification Code",
                      "_3": "3",
                      "_2": "2",
                      "_1": "1",
                      "_4": "4",
                      "_6": "6",
                      "_7": "7",
                      "_9": "9",
                      "_8": "8",
                      "_0": "0",
                      "_5": "5",

                      "currency": "Currency",
                      "trusted_device": "Trusted device",
                      "change": "Change",
                      "delete": "Delete",
                      "delete_trusted_device_success": "Delete trusted device success",
                      "delete_trusted_device_fail": "Delete trusted device fail",
                      "new_group_name": "New contract group name",
                      "market_value_title": "Market Value",
                      "initial_margin_title": "IM",
                      "add": "Add",
                      "manage": "Manage",
                      "memo": "Memo",

                      "agree": "Agree",
                      "disagree": "Disagree",
                      "user_services_and_privacy_terms_tip": 'Please carefully read and fully understand the 《Ping An Futures Privacy Policy Agreement》. If you agree, please click Agree " to start accepting our services.',

                      "user_services_and_privacy_terms_title": "User services and privacy terms",
                      "create_time": "Create time %s",
                      "expiry_time": "Expiry time %s",

                      "trade_account": "Trade Account",

                      "order_success": "Order successfully",
                      "check_new_order_details": "Check details",
                      "note_star": "* Note: ",
                      "note": "Note",
                      "turn_on_now": "Turn on now",
                      "settings_permissions_reminder_content": "Please turn on【location】and【access device information】(or 【phone】) permissions in settings to continue login.",

                      "check_it_later": "If you don\'t see the order in the list, please check it later.",

                      "order_title": "Order",
                      "working_order": "Working",
                      "filled_order": "Filled",
                      "order_id": "Order ID：%s",
                      "ordered_id": "Order ID",

                      "filled_lots_total_lots": "Filled lots / Total lots",

                      "working_": "Working",
                      "working_partial_filled": "Partial filled",
                      "filled_": "Filled",
                      "working_pending_new": "Pending new",
                      "working_replaced": "Replaced",
                      "expired": "Expired",
                      "calculated": "Calculated",
                      "stopped": "Stopped",
                      "canceled": "Canceled",
                      "unknown_status": "Unknown status",
                      "exec_id": "Exec ID：%s",
                      "executed_id": "Exec ID",
                      "maintenance_margin": "MM",
                      "change_account": "Change account",
                      "change_currency": "Change currency",
                      "default_exposure": "Default",
                      "convert_exposure": "Convert",
                      "selected_contracts": "Selected contracts",
                      "fragment_title_quote": "Quote",
                      "illegal_max_iceberg_chunk_size": "Ill Max Iceberg Chunk Size",
                      "chunk_size_cant_be_larger_than_lots": "Chunk size can\'t be larger than lots",
                      "assets_title_broker": "Broker assets",
                      "assets_title_account": "Account assets",

                      "position_today_buy_lots": "Today buy lots",
                      "position_today_buy_price": "Today buy price",
                      "position_today_sell_lots": "Today sell lots",
                      "position_today_sell_price": "Today sell price",
                      "position_bid": "Bid",
                      "position_offer": "Offer",
                      "position_profit_and_loss": "Profit and loss",

                      "position_long": "Long",
                      "position_short": "Short",
                      "position_last_price": "LTP",
                      "position_last_upl": "PositionPL",
                      "position_last_pl": "ClosePL",
                      "position_net_lots": "Net Lots",
                      "position_net_price": "Net Price",
                      "pending_new_edit_tip": "Pending new order can\'t be amended or canceled.",
                      "position_title": "Position",
                      "confirm_direction": "Side",
                      "confirm_contract": "Contract",
                      "no_contract_add_tip": "No contracts in this group, please press the \"+\" below to add new contract",
                      "no_contract_tip": "No contracts in this group",
                      "no_search_results": "No search results",
                      "keyword_to_search_tip": "Exchange name \\ Product name \\ Contract code",
                      "done_added": "&#160;&#160;&#160;Done&#160;&#160;&#160;",
                      "selected_count": "(Selected %d)",
                      "please_enter_more_than_one_character": "Please enter more than one character.",
                      "transaction_direction": "Side",
                      "please_change_the_order_parameter": "Please change the order parameter.",
                      "add_new_contract_group_successfully": "Adding new contract group successful",
                      "add_new_contract_group_failed": "Adding new contract group failure",
                      "group_name_already_exists_tip": "The contract group \"%s\" exists.",
                      "group_name_already_exists_tip_case_insensitive": "The contract group \"%s\" exists (case insensitive)",
                      "maximum_characters_length_is_15": "The maxmium input characters count is 15",
                      "show": "SHOW",
                      "hide": "HIDE",
                      "login_change_password": "Change password?",
                      "when_value_up_and_down_the_color_changes": "The color changes when quote value goes up or down",

                      "confirm_order_lots": "Lots",
                      "confirm_order_2_limit": "Price",
                      "confirm_order_type": "Type",
                      "confirm_order_stop_price": "StPx",
                      "confirm_order_maxIcebergChunkSize": "Max chunk size",
                      "confirm_order_hedge_flag": "Hedge flag",
                      "confirm_order_offset_flag": "Offset flag",
                      "confirm_order_expiry_time": "Expiry time",

                      "no_filled_orders_today": "No filled orders today",
                      "no_orders": "No working orders",
                      "no_messages": "No messages",
                      "play_voice_hint": "Play voice hint",
                      "change_language": "Change language",
                      "set_quote_color": "Set quote color",
                      "user": "User",
                      "system": "System",
                      "voice_hint_tip": "The voice of new order, order filled etc.",
                      "version": "Version",
                      "confirm_new_password": "Confirm new password",
                      "change_server": "Change server",
                      "search_contract_history": "Search contract results history:",
                      "contract": "Contract",
                      "contract_code": "Contract code",
                      "delete_search_history": "Are you sure to delete this search records?",
                      "delete_contracts": "Are you sure to delete the selected contracts?",

                      "filled_order_list_detail": "Detail(%d)",
                      "filled_order_list_order": "Order id(%d)",
                      "filled_order_list_contract": "Contract(%d)",
                      "more": "More",
                      "list": "List",
                      "timeline": "Timeline",
                      "no_position_data": "No position data",
                      "operations_cancel_order": "Cancel order",
                      "go_to_modify": "Go to modify",
                      "order_details": "Order details",
                      "please_input_lots": "Please input lots",
                      "rename_contract_group_successfully": "Renaming contract group successful",
                      "rename_contract_group": "Rename contract group",
                      "rename_contract_group_failure": "Renaming contract group failure",
                      "add_new_contracts_successfully": "Adding new contracts successful",
                      "contract_doesnt_exist": "Contract doesn\'t exist",
                      "the_default_is_the_system_language": "The default is the system language",
                      "collapse": "Collapse",
                      "the_maximum_number_of_contracts_is_50": "The maximum number of contracts is 50",
                      "this_contract_group_has_maxmium_number_of_contracts": "This contract group has maxmium number of contracts",
                      "contract_list_header_close_trend": "Close trend",
                      "finished": "Finished",
                      "order_tip_filled": "Filled&#160;",
                      "lots_and_price": "%1$s @ %2$s",
                      "order_tip_contract_code": "Contract code: %s",
                      "order_tip_filled_info_lots": "Lots: %1$s",
                      "order_tip_filled_info": "Lots: %1$s&#160;&#160;Filled lots: %2$s&#160;&#160;AvgPx: %3$s",

                      "position_buy_lots": "Buy Lots",
                      "position_sell_lots": "Sell Lots",
                      "position_broker_name": "%1$s_%2$s(%3$d)",
                      "all": "All",
                      "filter": "Filter",
                      "the_value_cannot_be_empty": "The value can\'t be empty",
                      "the_string_value_cannot_be_empty": "%s: The value can\'t be empty",
                      "contract_group_contains_at_least_one_contract": "Contract group contains at least one contract",
                      "the_last_contract_group_cannot_be_deleted": "The last contract group can\'t be deleted",
                      "relogin_or_logout_disconnect_tip": "Your account might be logged in on other devices or time out, please log in again",
                      "logged_out": "Logged out",
                      "add_into_one_of_the_contract_groups_below": "Add %s into one of the contract groups below",
                      "already_exist_in_the_following_contract_groups": "%s already exist in the following contract groups",
                      "choose": "Choose",
                      "strategy_title": "Strategies",
                      "ratio_1": "Ratio1",
                      "ratio_2": "Ratio2",

                      "times": "Times",
                      "single_trigger_times": "STT",
                      "executed": "Executed",
                      "protection": "Protection",
                      "single_trigger_number_full": "Single trigger number",

                      "execution_number": "Execution number",
                      "send": "Send",
                      "normal_type": "Normal",
                      "none": "None",
                      "type_1": "Type 1",
                      "type_2": "Type 2",
                      "reference_price": "RefPx",
                      "reference_price_bid": "Best Bid",
                      "reference_price_offer": "Best Offer",
                      "reference_price_average": "Avg Bid &amp; Offer",
                      "reference_price_last_trade": "Last Trade",
                      "reference_price_opponent": "Best Bid / Offer",
                      "illegal_single_trigger_number": "Single trigger number is illegal",
                      "illegal_execution_number": "Illegal execution times",
                      "lots_number_is_illegal": "Lots is illegal",
                      "price_number_is_illegal": "Diff is illegal",
                      "order_request_sent_successfully": "Order request sent successfully!",
                      "new_strategy_order": "New strategy order",
                      "single_trigger_times_must_be_below_execution_number": "Single trigger times must be smaller than or equal to execution number",
                      "expiry_date_is_illegal": "Expiry date is illegal",
                      "broker_status_title": "Broker status",
                      "lot_price_diff_regax": "L:%s D:%s",
                      "order_range": "Order range",
                      "always_best_price": "Always best price",
                      "active_better": "Active better",
                      "active_worse": "Active worse",
                      "max_500": "(max 500)",
                      "order_range_cannot_be_empty": "Order range can\'t be empty",
                      "active_better_cannot_be_empty": "Active better can\'t be empty",
                      "active_worse_cannot_be_empty": "Active worse can\'t be empty",
                      "illegal_order_range": "Illegal order range",
                      "illegal_active_better": "Illegal active better",
                      "illegal_active_worse": "Illegal active worse",
                      "the_input_order_range_value_is_out_of_the_range": "The input order range value is out of the range",
                      "the_input_active_better_value_is_out_of_the_order_range": "The input active better value is out of the order range",
                      "the_input_active_worse_value_is_out_of_the_order_range": "The input active worse value is out of the order range",
                      "the_price_difference_must_be_the_integer_times_of_the_minimal_price_of_tick_size": "Diff must be the integer times of the minimal price of tick size",
                      "the_price_must_be_the_integer_times_of_the_minimal_price_of_tick_size": "The price must be the integer times of the minimal price of tick size",
                      "please_select": "Please select",
                      "please_select_a_type_of_reference_price": "Please select a type of reference price",
                      "the_active_leg_lots_must_be_greater_than_0": "The active leg lots must be greater than 0",
                      "the_prior_leg_lots_must_be_greater_than_0": "The prior leg lots must be greater than 0",
                      "the_sum_of_all_lots_must_be_greater_than_0": " The sum of all lots must be greater than 0",
                      "select_contract": "Select contract",
                      "please_input_formula": "Please input formula",
                      "please_input_strategy_name": "Please input strategy name",
                      "strategy_name_cannot_be_empty": "Strategy name can\'t be empty",
                      "formula_cannot_be_empty": "Formula cannot be empty",
                      "formula_value_cannot_be_empty": "Formula value cannot be empty",
                      "add_new_strategy_successfully": "Adding new strategy successful",
                      "amending_strategy_successful": "Amending strategy successful",
                      "Please_select_contract": "Please select contract",
                      "add_strategy": "Add Strategy",
                      "formula_length_cannot_be_longer_than_127_characters": "Formula length can\'t be longer than 127 characters",
                      "input_length_cannot_be_longer_than_number_characters": "Input length can\'t be longer than %d characters",
                      "strategy_name_has_existed": "The strategy name \'%s\' exists (case insensitive)",
                      "pending_new": "Pending new",
                      "illegal_type_does_not_exist": "Illegal type, %s doesn\'t exist",
                      "no_protection": "No protection",
                      "leg_setting_format": "Range 1-%1$d｜Better %2$d｜Worse %3$d%4$s",
                      "strategy_order_id": "ID: %s",
                      "edit_strategy": "Edit Strategy",
                      "please_select_reference_price": "Please select reference price",
                      "please_select_contract_title": "Select Contract",
                      "no_strategies": "No strategies, please press the \"+\" below to add new strategy",
                      "k_chart_volume": "Volume",
                      "k_chart_open": "Open",
                      "k_chart_high": "High",
                      "k_chart_low": "Low",
                      "k_chart_close": "Close",
                      "k_chart_position": "Position",
                      "new_password_and_old_password_cannot_be_the_same": "New password and old password can’t be the same",
                      "please_input_new_password_again": "Please input new password again",
                      "current_password": "Current password",
                      "Please_input_your_current_password": "Please input your current password",
                      "new_password": "New password",
                      "close_up": "Close",
                      "last_limit_price": "Last limit price",

                      "strategy_order": "Strategy order",
                      "stop_order": "Stop order",
                      "gain_best_order": "Gain best order",
                      "stop_title": "Stop @",
                      "market_buy_price": "Market buy price",
                      "market_sell_price": "Market sell price",
                      "last_trade_price": "Last trade price",
                      "stop_price_text": "Stop price",
                      "lots_and_price_title": "Lots @ Price",
                      "normal_order": "Normal order",
                      "amend_order_request_has_sent": "Amend order request has sent",
                      "The_maximum_input_value_digit_is_8_integers": "The maximum input value digit is 8 integers.",
                      "the_maximum_input_value_digit_is_8_integers_and_8_decimals": "The maximum input value digit is 8 integers and 8 decimals",
                      "the_maximum_input_value_digit_is_count_integers": "The maximum input value digit is %s integers",
                      "the_maximum_input_value_digit_is_count_integers_and_count_decimals": "The maximum input value digit is %s integers and %s decimals",
                      "please_select_the_check_box_to_agree_to_collecting_the_required_information": "Please select the check box to agree to collecting the required information",
                      "empty_string": "",
                      "mode": "Mode",
                      "by_open_position_average_price": "By open position average price",
                      "by_custom_price": "By custom price(not open order)",
                      "close_px_diff": "Close Pxdiff",
                      "stop_loss": "Stop loss",
                      "stop_profit": "Stop profit",
                      "stop_profit_loss_order": "Stop profit loss order",
                      "open_px_diff": "Open Pxdiff",
                      "select_mode": "Select mode",
                      "select_type": "Select type",
                      "the_value_must_be_the_integer_times_of_the_minimal_price_of_tick_size": "%s must be the integer times of the minimal price of tick size",
                      "diff_the_value_must_be_the_integer_times_of_the_minimal_price_of_tick_size": "Diff must be the integer times of the minimal price of tick size",
                      "value_is_illegal": "%s is illegal",
                      "order_interval_value_is_illegal": "Order interval is illegal",
                      "cancel_interval_value_is_illegal": "Cancel interval is illegal",
                      "exchange_market_order": "Exchange market order",
                      "execute_lots": "Executed lots",
                      "filled_lots": "Filled lots",
                      "not_closed_average_price": "Not closed average price",
                      "not_close_lots": "Not closed lots",
                      "use_exchange_market_order": "Use exchange market order",
                      "please_input_price_diff": "Please input price diff",
                      "order_price": "Order price",
                      "base_price": "Base price",
                      "t_wap_price_type_last_trade": "Last trade",
                      "t_wap_price_type_market_buy": "Market buy",
                      "t_wap_price_type_market_sell": "Market sell",
                      "t_wap_price_type_opponent": "Best Bid / Offer",
                      "single": "Single",
                      "order_interval": "Order interval",
                      "cancel_interval": "Cancel interval",
                      "effect_immediately": "Effect immediately",
                      "always_execute": "Always execute",
                      "t_wap_order": "TWAP order",
                      "start": "Start",
                      "end": "End",
                      "cancel_limit": "Cancel limit",
                      "price_limit": "Price limit",
                      "please_input_seconds": "Please input seconds",
                      "single_lots_must_be_smaller_than_or_equal_to_lots": "Single lots must be smaller than or equal to lots",
                      "single_lots": "Single lots",
                      "price_type": "Price type",
                      "the_end_time_must_be_later_than_now": "The end time must be later than now",
                      "total_lots": "Total lots",
                      "price_difference": "Diff",
                      "filled_average_price": "Filled average price",
                      "executed_order_times": "Executed order times",
                      "executed_cancel_times": "Executed cancel times",
                      "select_price_type": "Select price type",
                      "The_start_time_must_be_before_the_end_time": "The start time must be before the end time",
                      "the_cancel_interval_must_be_smaller_than_or_equal_to_order_interval": "Cancel interval must be smaller than or equal to order interval",
                      "last_order_time": "Last order time",
                      "no_auto_order_currently": "No %s currently",
                      "time_interval": "Time interval",
                      "timing_order_title": "Timing order",
                      "hour_minute_second_description": "H \'h\' m \'m\' s \'s\'",
                      "time_interval_is_illegal": "Time interval is illegal",
                      "executed_times": "Executed times",
                      "executed_times_": "Executed times",
                      "last_executed_lots": "Last executed lots",
                      "hour": "h",
                      "minute": "m",
                      "second": "s",
                      "no_content_tip_gain_best_order": "gain best order",
                      "no_content_tip_stop_order": "stop order",
                      "please_input_value": "Please input %s",
                      "risk_check_failed": "Risk check failed",

                      "history_filled": "Filled",
                      "history_trade": "Trade",
                      "history_today": "Today",
                      "history_yesterday": "Yesterday",
                      "history_last_7_days": "Latest 7 days",
                      "history_custom": "Custom",
                      "order_history": "Order history",
                      "history_search": "Search",
                      "order_id_title": "Order ID",
                      "trade_date": "Trade date",
                      "order_time": "Order time",
                      "filled_time": "Filled time",
                      "id_format": "ID %s",
                      "filled_order_detail": "Filled order detail",
                      "trade_order_detail": "Trade order detail",
                      "order_status": "Order status",
                      "avg_filled_price": "Avg filled price",
                      "the_operation_is_too_frequent": "The operation is too frequent",
                      "time_range_is_out_of_limit": "Time range is out of limit(1 week)",
                      "date_is_out_of_limit": "Date is out of limit(Last 1 month)",
                      "rejected": "Rejected",
                      "triggered_by_auto_order": "(* Triggered by auto order)",
                      "time_in_force_abbreviation": "TIF",
                      "market_english": "Market",
                      "expire_time_": "Expiry Time",
                      "the_start_time_must_be_before_the_end_time": "The start time must be before the end time",
                      "sell_order_stpx_must_be_greater_than_or_equal_to_trigger_price": "Sell order StPx must be greater than or equal to trigger price",
                      "buy_order_stpx_must_be_smaller_than_or_equal_to_trigger_price": "Buy order StPx must be smaller than or equal to trigger price",
                      "available": "Available",
                      "please_select_formula_operator": "Please select formula operator",
                      "no_data": "No data",
                      "account_title": "Account",
                      "remember_password": "Remember password",
                      "delete_strategy_success": "Delete strategy success",
                      "delete_strategy_fail": "Delete strategy fail",
                      "new_strategy_order_fail": "New strategy order fail",
                      "add_strategy_fail": "Add strategy fail",
                      "edit_strategy_fail": "Edit strategy fail",
                      "delete_contract_group_fail": "Delete contract group fail",
                      "password_expired_tip": "Your password will be expired in %d days!",
                      "buy_average_price": "Buy Average Price",
                      "sell_average_price": "Sell Average Price",
                      "buy_profit": "Buy Profit",
                      "sell_profit": "Sell Profit",
                      "unknown_device": "Unknown device",
                      "t_plus_one": "T+1",


                      



                      }
